_wandb:
    value:
        cli_version: 0.25.1
        e:
            ozvyjkham12e12h6fmovx264d5x7cbr7:
                codePath: ai-agent\train.py
                codePathLocal: ai-agent\train.py
                cpu_count: 6
                cpu_count_logical: 6
                disk:
                    /:
                        total: "498657652736"
                        used: "392730329088"
                email: yshirokov05@gmail.com
                executable: C:\Projects\rust-rl-agent\venv\Scripts\python.exe
                git:
                    commit: 1f8bb0559731c22c159a2c101444091eb2eec787
                    remote: https://github.com/yshirokov05/rust-rl-agent
                host: DESKTOP-LRTP7RS
                memory:
                    total: "34302423040"
                os: Windows-11-10.0.26200-SP0
                program: C:\Projects\rust-rl-agent\ai-agent\train.py
                python: CPython 3.12.6
                root: C:\Projects\rust-rl-agent
                startedAt: "2026-03-19T21:00:02.685181Z"
                writerId: ozvyjkham12e12h6fmovx264d5x7cbr7
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 5
                - 13
                - 14
                - 62
            "4": 3.12.6
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
